# Generated by Django 5.0.6 on 2024-05-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fishes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fish",
            name="taste",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="fish",
            name="texture",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="fishcategory",
            name="taste",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="fishcategory",
            name="texture",
            field=models.TextField(null=True),
        ),
    ]
