# Generated by Django 5.0.6 on 2024-05-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fishes", "0002_fish_taste_fish_texture_fishcategory_taste_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fish",
            name="image",
        ),
        migrations.RemoveField(
            model_name="fishcategory",
            name="image",
        ),
        migrations.AddField(
            model_name="fish",
            name="image1",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="fish",
            name="image2",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="fish",
            name="image3",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="fishcategory",
            name="image1",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="fishcategory",
            name="image2",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="fishcategory",
            name="image3",
            field=models.URLField(null=True),
        ),
    ]
