# Generated by Django 4.1.2 on 2024-06-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fishes", "0005_remove_fishcategory_image1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fish",
            name="image1",
        ),
        migrations.RemoveField(
            model_name="fish",
            name="image2",
        ),
        migrations.RemoveField(
            model_name="fish",
            name="image3",
        ),
        migrations.AddField(
            model_name="fish",
            name="image_urls",
            field=models.JSONField(default=list, null=True),
        ),
    ]
